# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: hostctl
builds:
  - id: hostctl
    binary: hostctl
    main: cmd/hostctl/main.go
    env:
      - GO111MODULE=on
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/guumaster/hostctl/pkg/cmd/cmd.version={{.Version}}

changelog:
  sort: desc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^tests:'
      - '^Scoop update'
      - '^ci:'
      - Merge pull request
      - Merge branch

archives:
  - format_overrides:
      - goos: windows
        format: zip
    replacements:
      amd64: 64-bit
      darwin: macOS

before:
  hooks:
    - go mod tidy

release:
  github:
    owner: guumaster
    name: hostctl

nfpms:
  - id: hostctl
    builds:
      - hostctl
    formats:
      - deb
    vendor: Guumaster
    homepage: https://github.com/guumaster/hostctl
    maintainer: guumaster <guuweb@gmail.com>
    description: Your dev tool to manage /etc/hosts like a pro

brews:
  - name: hostctl
    github:
      owner: guumaster
      name: homebrew-tap
    homepage:  https://github.com/guumaster/hostctl
    description: Your dev tool to manage /etc/hosts like a pro
    commit_author:
      name: goreleaserbot
      email: guuweb@gmail.com
    caveats: "Remember to add sudo to modify your hosts file."

scoop:
  bucket:
    owner: guumaster
    name: hostctl
  homepage:  https://github.com/guumaster/hostctl
  description: Your dev tool to manage /etc/hosts like a pro
  license: MIT

snapcrafts:
  - id: hostctl
    name: hostctl
    summary: Your dev tool to manage /etc/hosts like a pro
    description: Your dev tool to manage /etc/hosts like a pro.
    grade: stable
    confinement: strict
    license: MIT
    publish: true
    apps:
      hostctl:
        plugs: ["network-control"]
