# This file was generated by GoReleaser. DO NOT EDIT.
class Hostctl < Formula
  desc "manage your hosts file like a pro"
  homepage "https://github.com/guumaster/hostctl"
  version "0.5.0-dev"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/guumaster/hostctl/releases/download/v0.5.0-dev/hostctl_0.5.0-dev_macOS_64-bit.tar.gz"
    sha256 "a58fb04bbc122cc85991bc5d018b49a38eab25c29f6fb8be48675db9b833c953"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/guumaster/hostctl/releases/download/v0.5.0-dev/hostctl_0.5.0-dev_linux_64-bit.tar.gz"
      sha256 "6a1db3964ae102309b6f0c639d2c1fab3f6b39d1281ff1a6492eb35c1f56f03b"
    end
  end

  def install
    bin.install "hostctl"
  end

  def caveats; <<~EOS
    Remember to add sudo to modify your hosts file.
  EOS
  end
end
