name: github pages

on:
  push:
    branches:
      - docs

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: docs
          submodules: true

      - name: Get contributors
        run: |
          git fetch origin master
          git checkout origin/master -- .all-contributorsrc
          cp .all-contributorsrc docs/data/contributors.json

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16.x

      - name: Generate CLI docs
        env:
          LINKS_PREFIX: "/hostctl"
        run: |
          go run ./cmd/hostctl/main.go gen-md-docs --path docs/content/docs/cli-usage

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.85.0'
          extended: true

      - name: Build site
        run: |
          cd docs
          hugo --minify --enableGitInfo

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/public
          force_orphan: true
          enable_jekyll: true
          publish_branch: gh-pages
