on:
  push:
    branches-ignore:
      - allcontributors/**
      - docs
      - gh-pages
  pull_request:
    branches:
      - '*'

name: Lint
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install golangci-lint
        run: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.33.0

      - name: Install golint
        run: go get -u golang.org/x/lint/golint

      - name: Run golangci-lint
        run: $(go env GOPATH)/bin/golangci-lint run ./...  --timeout 5m

      - name: Run golint
        run: $(go env GOPATH)/bin/golint ./...
