on:
  push:
    branches-ignore:
      - allcontributors/**
      - docs
      - gh-pages
  pull_request:
    branches:
      - '*'

name: Lint
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.48
